name: Docker

on:
  push

jobs:
  build_project_docker:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Build and push the image
      run: 
        docker login --username ${{ secrets.LOGIN }} --password ${{ secrets.PASSWORD }} ghcr.io
        docker build . --tag ghcr.io/${{ secrets.LOGIN }}/docker-container:latest
        docker push ghcr.io/${{ secrets.LOGIN }}/docker-container:latest
        docker run ghcr.io/${{ secrets.LOGIN }}/docker-container:latest